//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDonHang
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Incomes = new HashSet<Income>();
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int ID { get; set; }
        public string Code { get; set; }
        public int CustomerID { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public int PaymentTypeID { get; set; }
        public int DeliveryTypeID { get; set; }
        public string Note { get; set; }
        public decimal TotalMoney { get; set; }
        public decimal VAT { get; set; }
        public decimal PrePayment { get; set; }
        public decimal FinalMoney { get; set; }
        public string ExportDate { get; set; }
        public int IsDeleted { get; set; }
        public int CreateUser { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int UpdateUser { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string OrderDate { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual DeliveryType DeliveryType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Income> Incomes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual PaymentType PaymentType { get; set; }
    }
}
