//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDonHang
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public int CustomerID { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public int PaymentTypeID { get; set; }
        public int DeliveryTypeID { get; set; }
        public int Hours { get; set; }
        public int Minutes { get; set; }
        public string Note { get; set; }
        public decimal TotalMoney { get; set; }
        public decimal VAT { get; set; }
        public decimal PrePayment { get; set; }
        public decimal FinalMoney { get; set; }
        public System.DateTime ExportDate { get; set; }
        public int IsDeleted { get; set; }
        public int CreateUser { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int UpdateUser { get; set; }
        public System.DateTime UpdateDate { get; set; }
    }
}
